Fix using scoop shims
Scoop uses ps1 shims to run installed applications, getting command will try to execute the script instead of the real application resulting in

```
MethodInvocationException: C:\Users\<redacted>\Documents\PowerShell\Modules\BuildHelpers\2.0.11\Public\Invoke-Git.ps1:103
Line |
 103 |      $null = $p.Start()
     |      ~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."
```